### PR TITLE
Add code highlighting to Readme

### PR DESCRIPTION
**Pull request by iainsmith**

### CODE REVIEW

**Comment by NSProgrammer** [comment]
Good addition, easy PR to merge.  Please accept the review and accept the CLA and this can be merged.

**Comment by iainsmith** [comment]
I’d rather not hold up this change, so I’m closing this PR as I don’t have time to review the CLA right now.

**Comment by NSProgrammer** [comment]
No worries.  I'll get this change in from our end.  Cheers!

**Comment by NSProgrammer** [comment]
Merged: https://github.com/twitter/ios-twitter-network-layer/commit/64eda7b5162c356cf639dd160f8b3dc2909dfa99

**Pull request closed without merging**
